<?php

/**
 * @file
 *
 * Finanzen module
 */
 
/**
* Implements hook_perm().
*/
function finanzen_perm ()
{
  return array ('administer finanzen', 'add hours to projects');
}

/**
* Implements hook_init().
*/
function finanzen_init(){
  drupal_add_css(drupal_get_path('module', 'finanzen') .'/css/finanzen.css');
}

/**
* Implements hook_help().
*/

#function resourcereservation_help ( $path, $arg )
#{
#  $output=''; // para construir la salida
#  switch ( path )
#  {
#    case 'admin/help#resourcereservation':
#      $output .= '<p>' . t('Módulo que permite la reserva de recursos.') . '</p>';
#      break;
#  }
#  return $output;
#}

/**
 * Implements hook_menu().
 */
function finanzen_menu() {

  $items = array();

  $items['timesheet'] = array (
    'title' => t('List of User timesheet per Month'),
    'description' => 'The module information page',
    'page callback' => 'finanzen_mainpage',
    'access arguments' => array('add hours to projects'),
    'type' => MENU_CALLBACK,
  );
  
  $items['timesheet/month/%'] = array (
    'title' => t('Finanzen timesheet'),
    'description' => 'Timesheet',
    'page callback' => 'finanzen_timesheet_month',
    'page arguments' => array ( 2 ),
    'access arguments' => array('add hours to projects'),
    'type' => MENU_CALLBACK,
  );
  
  /* Insert(project_id, date, user_id) */
  $items['timesheet/insert/%/%/%'] = array (
   'title' => t('Add hours to Project'),
   'page callback' => 'finanzen_insert',
   'page arguments' => array ( 2, 3, 4 ),
   'access arguments' => array('add hours to projects'),
   'type' => MENU_CALLBACK,
  );
  
  /* Update(id) */
  $items['timesheet/update/%'] = array (
   'title' => t('Add hours to Project'),
   'page callback' => 'finanzen_update',
   'page arguments' => array ( 2 ),
   'access arguments' => array('add hours to projects'),
   'type' => MENU_CALLBACK,
  );  
  
  /*  */
  $items['timesheet/edit-month/%'] = array (
   'title' => t('Modify Whole Month'),
   'page callback' => 'finanzen_whole_month',
   'page arguments' => array ( 2 ),
   'access arguments' => array('add hours to projects'),
   'type' => MENU_CALLBACK,
  ); 

  return $items;
}

/**
 * Implements hook_theme().
 */
function finanzen_theme() {
  return array (
    'finanzen_whole_month_form_theme' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

/**
 * This function calculates next month in the calendar 
 */
function _finanzen_get_next_month(&$month, &$year)
{ 
  if ($month == 12) { $year++; $month=1; } else { $month++; }
}

/**
 * This function calculates previous month in the calendar 
 */
function _finanzen_get_previous_month(&$month, &$year)
{ 
  if ($month == 1) { $year--; $month=12; } else { $month--; }
}

/**
 * This function calculates the first day of the current month for a given $date
 */
function _finanzen_first_day_month($date)
{
  $month = date('m', $date);
  $year = date('Y', $date);
  return mktime(0,0,0,$month, 1, $year);
} 


/**
 * This function calculates next months first day in unix timestamp
 */
function _finanzen_get_first_day_next_month($date)
{
  $month = date('m', $date);
  $year = date('Y', $date);
  _finanzen_get_next_month($month, $year);
  return mktime(0,0,0,$month, 1, $year);
} 

/**
 * This function calculates previous months first day in unix timestamp
 */
function _finanzen_get_first_day_previous_month($date)
{
  $month = date('m', $date);
  $year = date('Y', $date);
  _finanzen_get_previous_month($month, $year);
  return mktime(0,0,0,$month, 1, $year);
} 

/**
 * This function calculates if the given date is weekend day
 */
function _finanzen_is_weekend($date)
{
  $weekday = date('N', $date);
  if ($weekday > 5) { 
    return TRUE; 
    
  } 
  else {
    return FALSE;  
  }
} 


/**
 * This function calculates how many days has a given month
 */
function _finanzen_days_in_month($month, $year)
{ 
  // calculate number of days in a month 
  return $month == 2 ? ($year % 4 ? 28 : ($year % 100 ? 29 : ($year % 400 ? 28 : 29))) : (($month - 1) % 7 % 2 ? 30 : 31); 
} 

/**
 * This function calculates how many days has a given month
 */
function _finanzen_get_project_code($project_id)
{ 
  $project_node = node_load ($project_id);
  return ($project_node->field_project_code[0]["value"]);
} 

/**
 * The default page for /timesheet url, now showing some basic information
 */
function finanzen_mainpage() {

  $current_date = time ();
  
  global $user;
  $first_day_month = _finanzen_first_day_month($user->created);
  
  while ($first_day_month < $current_date) {
      $link = "timesheet/month/" . $first_day_month ;
	  $content = '<p>' . l ( date('F Y', $first_day_month), $link ) . '</p>' . $content;
	  $first_day_month = _finanzen_get_first_day_next_month($first_day_month);
  }
  
  return $content;
}


/**
 * This function outputs a month navigator
 */
function _finanzen_month_navigator($first_day_month)
{ 
  $content = "<p>";
  $content .= '<a href="/timesheet">List months</a>';
  
  $current_date = time ();
  $current_first_day_month = _finanzen_first_day_month($current_date);
  
  global $user;
  $user_first_day_month = _finanzen_first_day_month($user->created);
  
  if ($first_day_month > $user_first_day_month) {
  	  $content .= " | ";
	  $content .= '<a href="/timesheet/month/' . _finanzen_get_first_day_previous_month($first_day_month) . '">Previous month</a>';
  }
  
  if ($first_day_month < $current_first_day_month) {
      $content .= " | ";
	  $content .= '<a href="/timesheet/month/' . _finanzen_get_first_day_next_month($first_day_month) . '">Next month</a>';
  }
    
   $content .= "</p>";
   
   return $content;     
} 

/**
 * Users Timesheet for the given month -> $first_day_month
 */
function finanzen_timesheet_month( $first_day_month ) {

  global $user;
  
  $month = date('m', $first_day_month);
  $year = date('Y', $first_day_month);
  
  $content .= "<p>Time Sheet for " . $user->name . " / " . date('F Y', $first_day_month) . "</p>";
  
  $content .= _finanzen_month_navigator($first_day_month);
  
  $content .= '<p><a href="/timesheet/edit-month/' . $first_day_month . '">Modify whole month</a></p>';
  
  $number_days = _finanzen_days_in_month($month, $year);

  $all_projects = $user->og_groups;
  
  $array_header = array('date' => t("Date"));
  
  foreach ($all_projects as $project) {
    $array_header[] = _finanzen_get_project_code($project[nid]);
  }
  
  $rows = array ();
  
  for ($i = 1; $i <= $number_days; $i++) {
    $day = mktime(0,0,0,$month, $i, $year);
    $rowdata = array ();
    $rowdata['date'] = date('l, d.m.Y', $day);
        
    foreach ($all_projects as $project) {
      $link = "timesheet/insert/" . $project[nid] . "/" . $day . "/" . $user->uid ;
      $query = "SELECT fuhp.nid, fuhp.hours FROM {finanzen_user_hours_projects} fuhp 
                WHERE fuhp.date=%d AND fuhp.uid=%d AND fuhp.project_id=%d" ;
      $queryResult = db_query ( $query, $day, $user->uid, $project[nid] );
      $resource = db_fetch_object ( $queryResult );
      
      if (($resource) && ($resource->hours != 0)){
        $link = "timesheet/update/" . $resource->nid ;
        $rowdata[$project[title]] = '<span class="inserted-time">' . round($resource->hours, 2) 
                                    . " hours</span> " . l ( t('Modify'), $link ) ;
      } 
      else {
        if ($resource->hours == 0) {
          $query_delete = "DELETE FROM finanzen_user_hours_projects WHERE nid='" . $resource->nid . "'";
          $query_deleteResult = db_query ( $query_delete );
        }
        $rowdata[$project[title]] = "Empty " . l ( t('Insert'), $link ) ;
      }
    }
    
    if (_finanzen_is_weekend($day))
      $row = array('data' => $rowdata, 'class' => "weekend");
    else
	  $row = array('data' => $rowdata);

    $rows[] = $row; 
  }
  
  $content .= theme_table($array_header, $rows);
  
  return $content;
}

/* --------------------- INSERT TIME - PROJECT --------------------------- */

function finanzen_insert ( $project_id, $date, $user_id )
{
  $content .= drupal_get_form ( 'finanzen_insert_form', $project_id, $date, $user_id  );
  return $content;
}

function finanzen_insert_form ( $form, $project_id, $date, $user_id )
{
  $human_date = date('l, d.m.Y', $date);
  $project_code = _finanzen_get_project_code($project_id);
 
  $form = array (
    'insert_time' => array (
      '#type' => 'fieldset',
      '#title' => t( 'How many hours did you work in the project <b>' . $project_code . '</b> on <b>' . $human_date . '</b> ?' ),
      'hours' => array ( '#type' => 'textfield',
                         '#title' => 'Hours',
                         '#maxlength' => 2,
                         '#default_value' => 0,
                         '#required' => TRUE,
                         '#prefix' => '<div class="insert-time-hours-field">',
                         '#suffix' => '</div>',
                       ),
      'minutes' => array ( '#type' => 'textfield',
                           '#title' => 'Minutes',
                           '#maxlength' => 2,
                           '#default_value' => 0,
                           '#required' => TRUE,
                           '#prefix' => '<div class="insert-time-minutes-field">',
                           '#suffix' => '</div>',
                         ),
      'project_id' => array ( '#type' => 'hidden', "#default_value" => $project_id ),
      'date' => array ( '#type' => 'hidden', "#default_value" => $date ),
      'user_id' => array ( '#type' => 'hidden', "#default_value" => $user_id ),
      'submit' => array ( '#type' => 'submit',  '#value' => t('Save'), ),
    ),
  );
  
  $form['#redirect'] = 'timesheet/month/' . _finanzen_first_day_month($date);
  
  return $form;
}

function finanzen_insert_form_submit ( $form, &$form_state )
{
  $user_id = $form_state['values']['user_id'];
  $date = $form_state['values']['date'];
  $hours = $form_state['values']['hours'];
  $minutes = $form_state['values']['minutes'];
  $project_id = $form_state['values']['project_id'];
  $hours_total = $hours + ((1/60) * $minutes);
  
  $query = "INSERT into {finanzen_user_hours_projects} ( uid, date, hours, project_id ) 
            values ( %d, '%s', %f, %d )";
  $queryResult = db_query ( $query, $user_id, $date, $hours_total, $project_id );
}

function finanzen_insert_form_validate($form, &$form_state) {
  if (($form_state['values']['hours'] > 24) || !(is_numeric($form_state['values']['hours']))) {
    form_set_error('hours', t('Hours: You must enter a numeric value between 0 and 24.'));
  }
    if (($form_state['values']['minutes'] > 59) || !(is_numeric($form_state['values']['minutes']))) {
    form_set_error('minutes', t('Minutes: You must enter a numeric value between 0 and 59.'));
  }
}

/* --------------------- UPDATE TIME - PROJECT --------------------------- */

function finanzen_update ( $id )
{
  $content .= drupal_get_form ( 'finanzen_update_form', $id );
  return $content;
}

function finanzen_update_form ( $form, $id )
{ 
  $query = "SELECT * FROM {finanzen_user_hours_projects} fuhp WHERE fuhp.nid=%d";
  $queryResult = db_query ( $query, $id );
  $resource = db_fetch_object ( $queryResult );
  
  $human_date = date('l, d.m.Y', $resource->date);
  $project_code = _finanzen_get_project_code($resource->project_id);

  $hours = intval($resource->hours);
  $minutes = round(($resource->hours - $hours) * 60, 0);
 
  $form = array (
    'update_time' => array (
      '#type' => 'fieldset',
      '#title' => t( 'How many hours did you work in the project <b>' . $project_code . '</b> on <b>' . $human_date . '</b> ?' ),
      'hours' => array ( '#type' => 'textfield',
                         '#title' => 'Hours',
                         '#default_value' => $hours,
                         '#maxlength' => 2,
                         '#required' => TRUE,
                         '#prefix' => '<div class="insert-time-hours-field">',
                         '#suffix' => '</div>',
                       ),
      'minutes' => array ( '#type' => 'textfield',
                           '#title' => 'minutes',
                           '#default_value' => $minutes,
                           '#maxlength' => 2,
                           '#required' => TRUE,
                           '#prefix' => '<div class="insert-time-minutes-field">',
                           '#suffix' => '</div>',
                         ),
      'id' => array ( '#type' => 'hidden', "#default_value" => $id ),
      'submit' => array ( '#type' => 'submit',  '#value' => t('Save'), ),
    ),
  );
  
  $form['#redirect'] = 'timesheet/month/' . _finanzen_first_day_month($resource->date);


  return $form;
}

function finanzen_update_form_submit ( $form, &$form_state )
{
  $id = $form_state['values']['id'];
  $hours = $form_state['values']['hours'];
  $minutes = $form_state['values']['minutes'];
  $hours_total = $hours + ((1/60) * $minutes);
  
  $query = "UPDATE finanzen_user_hours_projects SET hours='" . $hours_total . "' 
            WHERE nid='" . $id . "'";
  $queryResult = db_query ( $query );
}

function finanzen_update_form_validate($form, &$form_state) {
  if (($form_state['values']['hours'] > 24) || !(is_numeric($form_state['values']['hours']))) {
    form_set_error('hours', t('Hours: You must enter a numeric value between 0 and 24.'));
  }
    if (($form_state['values']['minutes'] > 59) || !(is_numeric($form_state['values']['minutes']))) {
    form_set_error('minutes', t('Minutes: You must enter a numeric value between 0 and 59.'));
  }
}

/* --------------------- Whole Month --------------------------------- */

function finanzen_whole_month ( $first_day_month )
{
  $content .= drupal_get_form ( 'finanzen_whole_month_form', $first_day_month );
  return $content;
}


function finanzen_whole_month_form ( $form, $first_day_month )
{
  // Clean the $form 
  $form = array ();
  
  global $user;
  
  $month = date('m', $first_day_month);
  $year = date('Y', $first_day_month);

  $all_projects = $user->og_groups;
  
  foreach ($all_projects as $project) {
    $project_node = node_load ($project[nid]);
  }
  
  $number_days = _finanzen_days_in_month($month, $year);
  
  for ($i = 1; $i <= $number_days; $i++) {

    $day = mktime(0,0,0,$month, $i, $year);
    
    foreach ($all_projects as $project) {  
      $query = "SELECT fuhp.nid, fuhp.hours FROM {finanzen_user_hours_projects} fuhp 
                WHERE fuhp.date=%d AND fuhp.uid=%d AND fuhp.project_id=%d" ;
      $queryResult = db_query ( $query, $day, $user->uid, $project[nid] );
      $resource = db_fetch_object ( $queryResult );
      
      if ($resource) {
        $hours = intval($resource->hours);
        $minutes = round(($resource->hours - $hours) * 60, 0);
        $css_class = "modified";
        $nid = $resource->nid;
      } 
      else {
        $hours = 0;
        $minutes = 0;
        $css_class = ""; 
        $nid = 0;
      }
      
      $project_code = _finanzen_get_project_code($project[nid]);
      
      $form['projects'][$day][$project[nid]] = array (
        'hours' => array ( '#type' => 'textfield',
                           '#title' => 'Hr',
                           '#default_value' => $hours,
                           '#maxlength' => 2,
                           '#weight' => 1,
                           '#prefix' => '<div class="insert-time-hours-field ' . $css_class . '">',
                           '#suffix' => '</div>',
                         ),
        'minutes' => array ( '#type' => 'textfield',
                             '#title' => 'Min',
                             '#default_value' => $minutes,
                             '#maxlength' => 2,
                             '#weight' => 2,
                             '#prefix' => '<div class="insert-time-minutes-field ' . $css_class . '">',
                             '#suffix' => '</div>',
                           ),
        'id' => array ( '#type' => 'hidden', "#default_value" => $nid ),
      );
    }
  }
  
  // Add submit button
  $form['submit'] = array (
      '#type' => 'submit',
      '#value' => t('Save'),
  );
  // Add theming function
  $form['#theme'] = 'finanzen_whole_month_form_theme';
  // This line is needed in order to keep the tree structure in form_state
  $form['projects']['#tree'] = TRUE;
  // Add redirection
  $form['#redirect'] = 'timesheet/month/' . $first_day_month;
  
  return $form; 

}

function theme_finanzen_whole_month_form_theme ( $form ) {
     
  $header = array('date' => t("Date"));
  
  $first_child = reset($form['projects']);
  
  $i=0;
  foreach (element_children($first_child) as $project_id) {
    $header[] = _finanzen_get_project_code($project_id);
    $projects[$i] = $project_id;
    $i++;
  }
  
  foreach (element_children($form['projects']) as $day) {
    $rowdata = array();
    $rowdata[] = date('l, d.m.Y', (float)$day);
    for ($j=0;$j<$i;$j++) {
	  $rowdata[] = drupal_render($form['projects'][$day][$projects[$j]]);
    }
      
    if (_finanzen_is_weekend($day))
      $row = array('data' => $rowdata, 'class' => "weekend");
    else
      $row = array('data' => $rowdata);
      
    $rows[] = $row;
  }
  
  // This is where we create the table using theme()
  $output .= theme('table', $header, $rows);
  
  $output .= drupal_render($form);
  return $output;

}

function finanzen_whole_month_form_validate ( $form, &$form_state ) {
  
  foreach (element_children($form_state['values']['projects']) as $date) {
    
    foreach (element_children($form_state['values']['projects'][$date]) as $project_id) {
    
      if (($form_state['values']['projects'][$date][$project_id]['hours'] != "") &&
          ($form_state['values']['projects'][$date][$project_id]['minutes']!= "")) {
    
        if (($form_state['values']['projects'][$date][$project_id]['hours'] > 24) ||
           !(is_numeric($form_state['values']['projects'][$date][$project_id]['hours']))) {
          form_set_error("projects][$date][$project_id][hours", t('Hours: You must enter a numeric value between 0 and 24.'));
        }
      
        if (($form_state['values']['projects'][$date][$project_id]['minutes'] > 59) ||
           !(is_numeric($form_state['values']['projects'][$date][$project_id]['minutes']))) {
          form_set_error("projects][$date][$project_id][minutes", t('Hours: You must enter a numeric value between 0 and 59.'));
        }
      }
    }
  }
}

function finanzen_whole_month_form_submit ( $form, &$form_state )
{
  global $user;
  
  foreach (element_children($form_state['values']['projects']) as $date) {
    
    foreach (element_children($form_state['values']['projects'][$date]) as $project_id) {
        
        $hours = $form_state['values']['projects'][$date][$project_id]['hours'];
        $minutes = $form_state['values']['projects'][$date][$project_id]['minutes'];
        $hours_total = $hours + ((1/60) * $minutes);
        
        $reg_id = $form_state['values']['projects'][$date][$project_id]['id'];
        
        if ($reg_id != 0) { // DB Register already exists
	      $query = "UPDATE finanzen_user_hours_projects SET hours='" . $hours_total . "' 
                    WHERE nid='" . $reg_id . "'";
          $queryResult = db_query ( $query );   
        } 
        else { // DB Register does not exists
          if (($form_state['values']['projects'][$date][$project_id]['hours'] != 0) ||
              ($form_state['values']['projects'][$date][$project_id]['minutes']!= 0)) {
	        $query = "INSERT into {finanzen_user_hours_projects} ( uid, date, hours, project_id )
                    values ( %d, '%s', %f, %d )";
            $queryResult = db_query ( $query, $user->uid, $date, $hours_total, $project_id );   
          }
        }
      
    }
  }
}

